# role-wf-submit.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflows-submit
  namespace: wf-poc
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-submit-bind
  namespace: wf-poc
subjects:
- kind: ServiceAccount
  name: default  # TODO <SENSOR_SA>
  namespace: argo-events
roleRef:
  kind: Role
  name: argo-workflows-submit
  apiGroup: rbac.authorization.k8s.io

