kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  kubeProxyMode: "iptables"  # Explicit mode
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80
  - containerPort: 30443
    hostPort: 443
  extraMounts:
    - hostPath: $PWD/landing-page-content
      containerPath: /var/www/docs
    - hostPath: $PWD/registrations
      containerPath: /var/registrations
