{{- if and (include "argo-stack.vault.enabled" .) .Values.externalSecrets.secrets.perAppS3 }}
{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1beta1/SecretStore" }}
{{- range $appName, $paths := .Values.externalSecrets.secrets.perAppS3 }}
{{- if and $paths.accessKeyPath $paths.secretKeyPath }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-cred-{{ $appName }}
  namespace: {{ $.Values.namespaces.tenant }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade     # <---- Annotations added here
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/component: argo-workflows
    argo-stack/application: {{ $appName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ include "argo-stack.secretStore.kind" $ }}
    name: {{ include "argo-stack.secretStore.name" $ }}
  target:
    name: s3-cred-{{ $appName }}
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: {{ $paths.accessKeyPath | replace "#" "/" }}
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ $paths.secretKeyPath | replace "#" "/" }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
