{{- if and (include "argo-stack.vault.enabled" .) .Values.events.enabled .Values.events.github.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.events.github.secret.name }}
  namespace: {{ .Values.events.namespace | default "argo-events" }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: argo-events
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ include "argo-stack.secretStore.kind" . }}
    name: {{ include "argo-stack.secretStore.name" . }}
  target:
    name: {{ .Values.events.github.secret.name }}
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: {{ .Values.events.github.secret.tokenKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.secrets.github.tokenPath | replace "#" "/" }}
{{- end }}
