{{- if and (include "argo-stack.vault.enabled" .) (index .Values "argo-cd" "enabled" | default true) }}
{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1/ClusterSecretStore" }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: {{ .Values.namespaces.argocd }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade     # <---- Annotations added here

  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ include "argo-stack.secretStore.kind" . }}
    name: {{ include "argo-stack.secretStore.name" . }}
  target:
    name: argocd-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: server.secretkey
      remoteRef:
        key: {{ .Values.externalSecrets.secrets.argocd.serverSecretKeyPath | replace "#" "/" }}
{{- if .Values.externalSecrets.secrets.argocd.ssoClientSecretPath }}
    - secretKey: oidc.clientSecret
      remoteRef:
        key: {{ .Values.externalSecrets.secrets.argocd.ssoClientSecretPath | replace "#" "/" }}
{{- end }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-initial-admin-secret
  namespace: {{ .Values.namespaces.argocd }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade     # <---- Annotations added here  
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ include "argo-stack.secretStore.kind" . }}
    name: {{ include "argo-stack.secretStore.name" . }}
  target:
    name: argocd-initial-admin-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.secrets.argocd.adminPasswordPath | replace "#" "/" }}
{{- end }}
{{- end }}
