{{- if include "argo-stack.vault.enabled" . }}
---
apiVersion: external-secrets.io/v1beta1
kind: {{ include "argo-stack.secretStore.kind" . }}
metadata:
  name: {{ include "argo-stack.secretStore.name" . }}
{{- if ne .Values.externalSecrets.vault.scope "cluster" }}
  namespace: {{ include "argo-stack.secretStore.namespace" . }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  provider:
    vault:
      {{- include "argo-stack.vault.backend" . | nindent 6 }}
      auth:
        {{- include "argo-stack.vault.auth" . | nindent 8 }}
{{- end }}
