{{- if include "argo-stack.vault.enabled" . }}
{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1/ClusterSecretStore" }}
---
apiVersion: external-secrets.io/v1
kind: {{ include "argo-stack.secretStore.kind" . }}
metadata:
  name: {{ include "argo-stack.secretStore.name" . }}
  namespace: {{ include "argo-stack.secretStore.namespace" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  provider:
    vault:
      {{- include "argo-stack.vault.backend" . | nindent 6 }}
      auth:
        {{- include "argo-stack.vault.auth" . | nindent 8 }}
{{- end }}
{{- end }}
