# Namespace where Argo CD is installed
argocdNamespace: argocd

# Prefix for workflow namespaces. For a repoUrl https://github.com/<org>/<repo>.git,
# the workflow namespace is assumed to be: <workflowNamespacePrefix><org>-<repo>
workflowNamespacePrefix: wf-

# Global group that should have full Argo CD admin privileges
adminGroup: wf-admins

# Source of truth for tenants. Each entry must include at least repoUrl.
# Example:
# repoRegistrations:
#   - name: bwalsh-nextflow-hello-project
#     repoUrl: https://github.com/bwalsh/nextflow-hello-project.git
#     defaultBranch: main
#     tenant: research-team-1
#     workflowTemplateRef: nextflow-repo-runner
#     artifactBucket:
#       hostname: $S3_HOSTNAME
#       bucket: $S3_BUCKET
#       region: $S3_REGION
#       insecure: true
#       pathStyle: true
#       keyPrefix: bwalsh-nextflow-hello-project-workflows/
#       externalSecretPath: argo/apps/bwalsh/nextflow-hello-project/s3/artifacts
#     githubSecretName: github-secret-bwalsh-nextflow-hello-project
#     githubSecretPath: argo/apps/bwalsh/nextflow-hello-project/github
#     adminUsers:
#       - pi@research.edu
#       - lead-scientist@research.edu
#     readUsers:
#       - postdoc@research.edu
#       - student@research.edu
#     isPublic: false
#
# The chart will derive:
#   org, repo       from repoUrl
#   appName         = <org>-<repo> (assumed Argo CD Application name)
#   projectName     = <org>-<repo> (assumed Argo CD Project name)
#   workflow ns     = <workflowNamespacePrefix><org>-<repo>
#   writer group    = wf-<org>-<repo>-writers
#   reader group    = wf-<org>-<repo>-readers
#
# NOTE: This chart does NOT create Applications, Projects or Namespaces.
#       It only creates RBAC resources that expect those to exist.

repoRegistrations: []
