# wf-poc/sensor-argo-events-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-events-workflow-access
  namespace: wf-poc
rules:
- apiGroups: ["argoproj.io"]
  resources:
    - workflows
  verbs: ["create", "get", "list", "watch"]
- apiGroups: ["argoproj.io"]
  resources:
    - workflowtemplates
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-workflow-access-binding
  namespace: wf-poc
subjects:
- kind: ServiceAccount
  name: default                  # ðŸ‘ˆ the SA in argo-events namespace
  namespace: argo-events
roleRef:
  kind: Role
  name: argo-events-workflow-access
  apiGroup: rbac.authorization.k8s.io

