apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextflow-launcher
  namespace: {{ .Values.namespaces.tenant }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextflow-executor
  namespace: {{ .Values.namespaces.tenant }}
rules:
  - apiGroups: ["", "batch"]
    resources: ["pods","pods/log","pods/status","jobs"]
    verbs: ["create","get","list","watch","delete","patch","update"]
  - apiGroups: ["argoproj.io"]
    resources:
      - workflows
      - workflowtemplates
      - cronworkflows
      - workflowtaskresults
      - workflowtasksets
      - workfloweventbindings
    verbs: ["create","get","list","watch","delete","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextflow-executor-binding
  namespace: {{ .Values.namespaces.tenant }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nextflow-executor
subjects:
  - kind: ServiceAccount
    name: nextflow-launcher
    namespace: {{ .Values.namespaces.tenant }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcm-lease-access
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get","list","watch","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcm-lease-access
subjects:
- kind: User
  name: system:kube-controller-manager
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: kcm-lease-access
  apiGroup: rbac.authorization.k8s.io
---
