apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextflow-launcher
  namespace: {{ .Values.namespaces.tenant }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextflow-executor
  namespace: {{ .Values.namespaces.tenant }}
rules:
  - apiGroups: ["", "batch"]
    resources: ["pods","pods/log","pods/status","jobs"]
    verbs: ["create","get","list","watch","delete","patch","update"]
  - apiGroups: ["argoproj.io"]
    resources:
      - workflows
      - workflowtemplates
      - cronworkflows
      - workflowtaskresults
      - workflowtasksets
      - workfloweventbindings
    verbs: ["create","get","list","watch","delete","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextflow-executor-binding
  namespace: {{ .Values.namespaces.tenant }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nextflow-executor
subjects:
  - kind: ServiceAccount
    name: nextflow-launcher
    namespace: {{ .Values.namespaces.tenant }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcm-lease-access
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get","list","watch","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcm-lease-access
subjects:
- kind: User
  name: system:kube-controller-manager
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: kcm-lease-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sensor-workflow-creator
  namespace: {{ .Values.namespaces.tenant }}
rules:
  # allow creating and managing Workflows
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
      - delete
  # allow reading WorkflowTemplates (so controller can reference templates if needed)
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtemplates"]
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-sensor-workflow-creator
  namespace: {{ .Values.namespaces.tenant }}
subjects:
  - kind: ServiceAccount
    name: wf-runner # change this to the SA your Sensor uses if not 'default'
    namespace: argo-events
roleRef:
  kind: Role
  name: sensor-workflow-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-sensor-workflow-creator-default
  namespace: {{ .Values.namespaces.tenant }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo-events
roleRef:
  kind: Role
  name: sensor-workflow-creator
  apiGroup: rbac.authorization.k8s.io  
